### ISSUE TITLE
Rebuild node-sass

### ISSUE THREAD

**Issue by cewert** [chingu-voyage4/Geckos-Team-22#13]
Doesn't work when using a windows environment

**Comment by cewert** [comment]
![capture](https://user-images.githubusercontent.com/16514652/37130056-e1455fc8-224f-11e8-9958-c220b65c76f1.PNG)

**Comment by jonager** [comment]
try using git bash

**Comment by cewert** [comment]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a8e065f9d7f5b0013d58811/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51a2737386e17ae71722040a0c1dac41590d46fcf9dc2ea5a42062c80d55b98e30063e937f03a6aa8317b500bf228b4a80b7ba8f4bc8e93c37aa.PNG)

The command works with git bash and it opened localhost:3000 in chrome, but the page is blank. No HTML. Nothing. Any ideas?

I'm going to install python and see what happens

**Comment by Skidragon** [comment]
@cewert  It's because the index.html does not have any html in it yet. if you type in localhost:3000/bello-board-home.html in the url then it will show that html page. localhost:3000 refers to the index.html. Anyway, I'm glad you got it working now :+1:
